planfixAccount: tagilcity
sendInterval: 60 # минут

# скопируйте в config.yml
apiToken:
workspaceId:

# for email send
sentTag: sent
smtpHost: smtp.yandex.ru
smtpPort: 587
smtpSecure: false
smtpLogin:
smtpPassword:
emailFrom:
planfixAuthorName:
planfixAnaliticName: Поминутная работа программиста

# for api send
planfixApiUrl: https://api.planfix.ru/xml/
planfixUserName:
planfixUserPassword:

debug: false
logFile: planfix-toggl.log
