sendInterval: 60 # минут

togglApiToken:
togglWorkspaceId:
togglSentTag: sent

# for email send
smtpHost: smtp.yandex.ru
smtpPort: 587
smtpSecure: false
smtpLogin:
smtpPassword:
smtpEmailFrom:
planfixAuthorName:
planfixAnaliticName: Поминутная работа программиста

# for api send
planfixAccount:
planfixApiUrl: https://api.planfix.ru/xml/
planfixUserName:
planfixUserPassword:

debug: false
logFile: planfix-toggl.log
